### ISSUE TITLE
ExposureTimeRatio

### ISSUE THREAD

**Issue by Semih67** [lovepark/ifm3d#104]
I noticed, if I increase the ExposureTime the camera has more insight. But the MaxAllowedFrameRate is affected by this. So what does the EposureTimeRatio exactly doing? Will this affect anything of the view of the camera if I change it?

**Comment by graugans** [comment]
@Semih67 the ``ExposureTime`` is the amount of time the camera illuminates the scene. So for _dark_ objects and objects which are far away from the camera this will enhance the visibility of those objects. For the O3X there is a trade-off, the more light is exposed the lower the frame rate can be. This is due to the fact that otherwise the VCSEL used in the camera is not eye safety any more.
