### ISSUE TITLE
3rdParty Directory?

### ISSUE THREAD

**Issue by tpanzarella** [lovepark/ifm3d#29]
@graugans Do you have insights on this *3rdParty* top-level directory? Is it needed any more? I think it was introduced as part of the Windows builds. However, I have not (yet) done a Windows build so I am unsure of its purpose. Let me know.

**Comment by graugans** [comment]
Yes it is, this is where the xmlrpc library needs to be checked out to. The XMLRPC find script in CMake is broken on windows. It relies on a script to locate the xmlrpc on the system. Due to the fact it is written in bash there is no way to get this running on a regular Windows installation. You can see my [PR|https://gitlab.kitware.com/cmake/cmake/merge_requests/1559] on the CMake project related to this issue. In my opinion the way to solve this is to use the CMake approach and create an [package configuration file](https://cmake.org/cmake/help/git-master/manual/cmake-packages.7.html#creating-packages) this is how for example GLog or Qt5+ handle things. But be warned using the package config approach breaks building of object libraries. See [my comment](https://github.com/google/glog/issues/4#issuecomment-351382259) on the GLog project for more details. So my idea is to add this package configuration file for my xmlrpc fork. Fixing the XMLRPCFind.cmake is another approach but this will take some time to be available to the broad audience. Any ideas?
