### ISSUE TITLE
XMLRPC Timeout

### ISSUE THREAD

**Issue by nhafez** [lovepark/ifm3d#76]
During the installation I encounter failed tests at the make check step.
I am not using the default IP and I can successfully ping it. As explained in this [issue](https://github.com/lovepark/libo3d3xx/issues/126) I changed the command to:
`$ IFM3D_IP=192.168.1.69 make check`
I still encounter the following failed tests:

> unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.MoveCtor (6010 ms)
[ RUN      ] Image.MoveAssignmentOperator
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.MoveAssignmentOperator (6009 ms)
[ RUN      ] Image.CopyCtor
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CopyCtor (6006 ms)
[ RUN      ] Image.CopyAssignmentOperator
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CopyAssignmentOperator (6008 ms)
[ RUN      ] Image.References
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.References (6010 ms)
[ RUN      ] Image.CloudMechanics
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CloudMechanics (6009 ms)
[ RUN      ] Image.XYZImage
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.XYZImage (6007 ms)
[ RUN      ] Image.ComputeCartesian
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.ComputeCartesian (6009 ms)
[ RUN      ] Image.TimeStamp
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.TimeStamp (3005 ms)
[ RUN      ] Image.IlluTemp
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.IlluTemp (3005 ms)
[----------] 10 tests from Image (54078 ms total)
[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (54078 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] Image.MoveCtor
[  FAILED  ] Image.MoveAssignmentOperator
[  FAILED  ] Image.CopyCtor
[  FAILED  ] Image.CopyAssignmentOperator
[  FAILED  ] Image.References
[  FAILED  ] Image.CloudMechanics
[  FAILED  ] Image.XYZImage
[  FAILED  ] Image.ComputeCartesian
[  FAILED  ] Image.TimeStamp
[  FAILED  ] Image.IlluTemp
10 FAILED TESTS

Any help is appreciated.

**Comment by graugans** [comment]
Have you tried to ping the camera? I expect an issue with your network set-up. Can you please post the output of the following commands? Assuming you are on a Linux box.

```
export IFM3D_IP=192.168.0.69
ping ${IFM3D_IP} -c 3
ip a
route -n
```

**Comment by nhafez** [comment]
Pinging works I get this:

> PING 192.168.24.31 (192.168.24.31) 56(84) bytes of data.
64 bytes from 192.168.24.31: icmp_seq=1 ttl=64 time=0.378 ms
64 bytes from 192.168.24.31: icmp_seq=2 ttl=64 time=0.488 ms
64 bytes from 192.168.24.31: icmp_seq=3 ttl=64 time=0.351 ms

> --- 192.168.24.31 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2045ms
rtt min/avg/max/mdev = 0.351/0.405/0.488/0.063 ms

second command output:

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 30:9c:23:72:2d:d9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.24.250/24 brd 192.168.24.255 scope global dynamic eno1
       valid_lft 796881sec preferred_lft 796881sec
    inet6 fe80::d7fc:f2f0:47b6:fcf4/64 scope link 
       valid_lft forever preferred_lft forever

third command output:

> Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.24.1    0.0.0.0         UG    0      0        0 eno1
0.0.0.0         192.168.24.1    0.0.0.0         UG    100    0        0 eno1
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eno1
192.168.24.0    0.0.0.0         255.255.255.0   U     100    0        0 eno1

**Comment by graugans** [comment]
In this case your make check command should look like this:

```
$ IFM3D_IP=192.168.24.31 make check 
```

**Comment by graugans** [comment]
Are you 100% sure there is no firewall or ip filter involved? Do you have a chance to grab a Windows Machine and test on Windows with the ifm Vision Assitant? 

Another thin you can try is to access the web interface of the camera by opening up the folowing URL in a web browser. 

[http://192.168.24.31/api/rpc/v1/com.ifm.efector/](http://192.168.24.31/api/rpc/v1/com.ifm.efector/)

Depending on your network policies the usage of [nmap](https://nmap.org/) to check if your camera has a different XML-RPC port assigned might come handy.

**Comment by nhafez** [comment]
yes, I had tested it with a windows machine and it worked fine. It turns out I needed to set a no_proxy for that ip adress and then it worked.

**Comment by graugans** [comment]
@nhafez Thanks for the hint with the ``no_proxy`` variable. We will add this to the documentation

**Comment by mathiasmantelli** [comment]
Hi @graugans, I'm experiencing the exactly same problem as @nhafez. I've setted my camera to IP 192.168.0.17, and if I ping that IP it works fine. I've tried your recommendations:

`$ export IFM3D_IP=192.168.0.69`
`$ ping ${IFM3D_IP} -c 3`
`$ ip a`
`$ route -n`

and the outputs are: 
-For `$ ping ${IFM3D_IP} -c 3`:
PING 192.168.0.69 (192.168.0.69) 56(84) bytes of data.
From 192.168.0.17 icmp_seq=1 Destination Host Unreachable
From 192.168.0.17 icmp_seq=2 Destination Host Unreachable
From 192.168.0.17 icmp_seq=3 Destination Host Unreachable

--- 192.168.0.69 ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2033ms
pipe 3

-For `$ ip a`:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 64:1c:67:79:81:5f brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.17/24 brd 192.168.0.255 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::1bb:5338:28da:8a8b/64 scope link 
       valid_lft forever preferred_lft forever
3: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 40:b8:9a:ff:b8:a3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.19/24 brd 192.168.0.255 scope global dynamic wlp2s0
       valid_lft 3121sec preferred_lft 3121sec
    inet6 2804:14d:4c89:8796::1006/128 scope global dynamic 
       valid_lft 2589918sec preferred_lft 2589918sec
    inet6 2804:14d:4c89:8796:3412:52ed:d93:aa21/64 scope global temporary dynamic 
       valid_lft 602697sec preferred_lft 83793sec
    inet6 2804:14d:4c89:8796:f168:2fb9:8627:10a6/64 scope global mngtmpaddr noprefixroute dynamic 
       valid_lft 2591992sec preferred_lft 604792sec
    inet6 fe80::81e2:59e:36b7:a48a/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:cf:7b:cb:7c brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

-For `$ route -n`:
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG    100    0        0 enp1s0
0.0.0.0         192.168.0.1     0.0.0.0         UG    600    0        0 wlp2s0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 docker0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.0.0     0.0.0.0         255.255.255.0   U     100    0        0 enp1s0
192.168.0.0     0.0.0.0         255.255.255.0   U     600    0        0 wlp2s0

Just to let you know, I've managed to make it work in another laptop, in which I followed the same tutorial to install [ifm3d-ros](https://github.com/ifm/ifm3d-ros/blob/master/doc/kinetic.md). Today I repeated the exactly same steps here in this new laptop (also Ubuntu 16.04 and ROS Kinetic), and I have this issue that I can't fix. The camera doesn't have a password, and all the cabes work fine. 

Any help is appreciated.

**Comment by inbangsa** [comment]
@mathiasmantelli as per your comment description you have changed the IP of camera to '''192.168.0.17'''  and IFM3D_IP variable to '''192.168.0.69'''. IFM3D_IP variable must have current IP address of device.  In your case you are setting it to '''192.168.0.69''' and hence your ping is not working.

If the device IP is set to '''192.168.0.17''' then you should export the following.

'''$export IFM3D_IP=192.168.0.17
$export no_proxy=192.168.0.17
'''

Please read our [troubleshoot](https://github.com/ifm/ifm3d/blob/master/doc/troubleshoot.md) guide for connection issues.

**Comment by mathiasmantelli** [comment]
Hi @inbangsa, thank you for your quick reply.

I'm aware of to this variable, and I just set it to 192.168.0.69 because  @graugans has recommended in one of his replies here. I exported, again, the variables as you suggested, and here is the output for this command `IFM3D_IP=192.168.0.17 make check`:

[ 18%] Built target ifm3d_camera
[ 31%] Built target ifm3d_framegrabber
[ 37%] Built target ifm3d_image
[ 43%] Built target gtest
[ 50%] Built target gtest_main
[ 59%] Built target ifm3d-image-tests
[==========] Running 10 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 10 tests from Image
[ RUN      ] Image.MoveCtor
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.MoveCtor (2 ms)
[ RUN      ] Image.MoveAssignmentOperator
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.MoveAssignmentOperator (0 ms)
[ RUN      ] Image.CopyCtor
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CopyCtor (1 ms)
[ RUN      ] Image.CopyAssignmentOperator
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CopyAssignmentOperator (0 ms)
[ RUN      ] Image.References
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.References (1 ms)
[ RUN      ] Image.CloudMechanics
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.CloudMechanics (1 ms)
[ RUN      ] Image.XYZImage
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.XYZImage (0 ms)
[ RUN      ] Image.ComputeCartesian
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.ComputeCartesian (0 ms)
[ RUN      ] Image.TimeStamp
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.TimeStamp (0 ms)
[ RUN      ] Image.IlluTemp
unknown file: Failure
C++ exception with description "Lib: XMLRPC Timeout - can you `ping' the sensor?" thrown in the test body.
[  FAILED  ] Image.IlluTemp (1 ms)
[----------] 10 tests from Image (7 ms total)

[----------] Global test environment tear-down
[==========] 10 tests from 1 test case ran. (7 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] Image.MoveCtor
[  FAILED  ] Image.MoveAssignmentOperator
[  FAILED  ] Image.CopyCtor
[  FAILED  ] Image.CopyAssignmentOperator
[  FAILED  ] Image.References
[  FAILED  ] Image.CloudMechanics
[  FAILED  ] Image.XYZImage
[  FAILED  ] Image.ComputeCartesian
[  FAILED  ] Image.TimeStamp
[  FAILED  ] Image.IlluTemp

10 FAILED TESTS
modules/image/test/CMakeFiles/check_image.dir/build.make:57: recipe for target 'modules/image/test/CMakeFiles/check_image' failed
make[3]: *** [modules/image/test/CMakeFiles/check_image] Error 1
CMakeFiles/Makefile2:927: recipe for target 'modules/image/test/CMakeFiles/check_image.dir/all' failed
make[2]: *** [modules/image/test/CMakeFiles/check_image.dir/all] Error 2
CMakeFiles/Makefile2:77: recipe for target 'CMakeFiles/check.dir/rule' failed
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
Makefile:184: recipe for target 'check' failed
make: *** [check] Error 2

Any ideas why is this error still happening? 
Thank you

**Comment by graugans** [comment]
Hey @mathiasmantelli sorry for the late response. I was out of office. Anyway from your output above I do see that you have configured both interfaces ``enp1s0`` and ``wlp2s0`` to the subnet `` 192.168.0.0/24 one with the IP ``192.168.0.17`` and the other with ``192.168.0.19``. From the routing the ``enp1s0`` has higher prio (as far as I do understand) maybe the camera is connected to the ``wlp2s0`` interface what would explain your issue IMHO.
